src/buf.c
This changes the sprintf function call to snprintf in buf.c, which is a safer string handling function. This is a downstream change from OpenBSD's version of flex.
=> buf.c: use snprintf

src/main.c
When using clang/llvm 3.8 to compile flex, the following warning is
emitted:
main.c:378:27: warning: the value of the size argument in 'strncat' is too large, might lead to a buffer overflow [-Wstrncat-size]
strncat(m4_path, m4, sizeof(m4_path));
^~~~~~~~~~~~~~~
main.c:378:27: note: change the argument to be the free space in the destination buffer minus the terminating null byte
strncat(m4_path, m4, sizeof(m4_path));
^~~~~~~~~~~~~~~
sizeof(m4_path) - strlen(m4_path) - 1
Fix it up by using the solution proposed by the warning message.
=> Fix potential buffer overflow in strncat()

src/scanflags.c
Currently, every call to sf_push() realloc()'s _sf_stack, even if the
maximum size _sf_max wasn't changed. As the indentation beneath the
"if" clause already indicates, the realloc() should only be executed
if _sf_max was increased.
Found by compiling flex with the -Wmisleading-indentation flags of gcc,
which leads to the following warning:
scanflags.c: In function ‘sf_push’:
scanflags.c:42:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (_sf_top_ix + 1 >= _sf_max)
^~
scanflags.c:44:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
_sf_stk = realloc(_sf_stk, sizeof(scanflags_t) * _sf_max);
^~~~~~~
=> Avoid realloc on every call of sf_push()

src/misc.c
This function was not used and always triggered a fatal error when run.
=> Delete action_m4_define from misc.c

src/scan.l
Previously, `[[` and `]]` were not escaped in strings, which led
to bad interactions with m4.
Also, don't break strings on newline, as GCC et al support whitespace
between a backslash and the subsequent newline.
=> Fix escaping of `[[` and `]]` in strings

doc/flex.texi
"Flex used to" was written twice at the beginning of Chapter 9, paragraph 2.
=> Update flex.texi: Removed repedative wording

.travis.yml, .travis/install-automake.sh, .travis/install-gettext.sh, NEWS
There are a number of non-usual things about flex -- from the fact that most tool chains assume that flex exists, which isn't true when building flex itself -- to the fact that some parts of flex are just down right self referential. To aid contributors in assessing the effects of their changes, to aid the maintainer in assessing changes, to ensure that flex continues to do what we all think it does, let's start testing flex's build.
=> continuous integration

tests/tableopts.am, tests/tableopts.sh
`$(LINK)` in Automake already contains the `-o $@` arguments.
=> test: Remove redundant '-o $@' in tableopts.am

src/scan.l
xgettext was not very clever at interpreting lex patterns and can get
confused when seeing unquoted quotation marks, and emit warnings for
them. Now fix the warnings by properly quoting the quotation marks in
lex regex patterns.
Example
Original: `\"[^"\n]*\"` -> "warning: unterminated string literal"
Fixed:    `"\""[^""\n]*"\""` -> OK
My basic build test shows that the generated stage1scan.c is
bit-identical to the original.
=> scanner: Fix scan.l xgettext warnings.

src/flex.skl
Commit a17d79e9c722a6735b6d2a8f152287404f27df32 defines `_POSIX_C_SOURCE`
to the minimum of 1 if it's not defined in the user's scanner code or
the compiling environment. However in glibc the macros are not yet set
up until one of the libc headers is included. This unfortunately have
made us overwrite the default `_POSIX_C_SOURCE` value that would be
defined by glibc (`200809L` at the time of writing), causing regressions
in user code.
Now in this patch:
1. Ensure feature test macros have been set up in glibc before checking
or defining any of them in our skeleton code.
2. Have a more conservative logic when determining the need to define
`_POSIX_C_SOURCE` (required for fileno()).
Fixes: #313
Note:
It could be tricky for application code to ensure feature test macros
have been set up in …
=> scanner: Fix glibc features.h dependency in skeleton

src/Makefile.am, tests/Makefile.am
1. Overwriting the files via `mv` command needs write permission on the directory, but the write permission on the file is not necessary. (In contrast, overwriting via `cp` command needs write permission on the file; write permission on the directory is optional.)
2. Make `mv` command more portable by specifying `-f` flag.
=> Makefile minor fixes

autogen.sh
* Don't silence `libtoolize --version` error messages. Silence the `--version` output instead.
* Let `autogen.sh` error message go to stderr.
* Don't quote the variable $LIBTOOLIZE when invoking it. This would allow invocation when `LIBTOOLIZE='a-future-libtoolize --gnu-compat';`.
=> autogen.sh fixes

configure.ac, src/flexdef.h, src/main.c
This reverts commit c34590c4bf067d4e749e5298a8ce9f90072d6332
and all search code patches that followed it.
The execvp() would do the $PATH searching of m4 for flex. There's no
need to duplicate the effort.
Another reason for the removal is to remove dependency on stat()
system call, which would cause a problem in a 32-bit OS accessing a
filesystem with 64-bit inode number (see #413).
=> Remove manual m4 search code. No more stat() dependency.

src/c99-flex.skl, src/cpp-flex.skl, src/go-flex.skl
When complied with 'gcc -O3', the yy_init_buffer call can confuse gcc,
thinking the 'b' pointer may be NULL. (gcc would warn that if
'-Wnull-dereference' is used). Fix the confusion by never pass a NULL
constant to the function.
Fixes: #377
=> scanner: Fix compiler confusion in yy_init_buffer()

src/cpp-flex.skl
`gcount()` is of type `streamsize` which has a system-dependent size with at least `int`. Because of the `int max_size` limit no bigger value will be returned, the explicit cast fixes warnings from compilers/static analyzers.
As an alternative `LexerInput` may be changed to have a return and parameter of type `streamsize`, but this would need more changes and likely create more warnings in other places.
This issue originates from https://github.com/lexxmark/winflexbison/issues/73 where more details can be found (this is not a MSVC only issue).
=> fix compile warning originating in cpp skeleton

src/c99-flex.skl, src/cpp-flex.skl, src/go-flex.skl
Many projects have pre-commit hooks that check for pedantic things like trailing whitespace. No harm in removing it to pacify them.
=> Remove trailing whitespace

doc/flex.texi
Correct character class equivalence examples.
Expand discussion of operators that lose special meaning within character classes.
See Issues #521 and #478.
=> doc(manual): Character classes

doc/flex.texi
It seems that the release number is `2.6.4` instead of `4.6.2`, and, there are some grammar issue in the doc.
=> fix some tiny doc errors.

doc/flex.texi
This PR fixes #369 by adding documentation about the option `--yymore`. 16ff9d01339a7ecd859ee619a8496ca878a3eb70 adds the main content, while e0e7091dc76d67a5b60647e4e0ddb45f8d7fa8bb adds references to other relevant areas of the documentation.
=> Add documentation about option '--yymore'

configure.ac
A build test is done to determine the minimum versions of the configure
tools (Autoconf, Automake, Libtool & gettext) that can successfully
build flex in the current state of the code. This commit would help
builders to figure out whether their build tools are still compatible
for building flex, or they need tools upgrade, especially when they
patch flex and need to regenerate configure script for any reason.
This commit resolves version requirement debates as in #374.
A summary of version requirements: Autoconf 2.62, Libtool 2.1b,
Automake 1.11.3 and gettext 0.19.6.
=> build: correct and document minimum Autotools reqirement in configure.ac

configure.ac
… fixes #386 
additional:
* don't check for GNU indent if indent-check already found no indent
* use common wording to check "*whether* $BINARY is GNU stuff"
You may pass a full path and/or a different name for the Bison executable and/or additional options for the bison executable now.
Tested with Cygwin and Trisquel.
=> remove hard-wired bison lookup, check for "GNU Bison" in $YACC's version output instead

tests/quotes.l
Issue #553 pointed out that we've lost some expressiveness in our comments due to the m4 quoting introduced about 7 years ago. The quoting was good and necessary, but we didn't notice the impact at the time.
This PR expands the quoting tests to cover the remaining edge cases (that I could find) in comment quoting so we'll be alerted in the future.
=> Extend m4 quoting tests for comments and actions

src/main.c
Currently, when the NULL-terminated variadic function `filter_create_ext()` is invoked, the value `0` is passed as the last argument to act as a terminator. However, this is an integer value, which is incompatible with the pointer data type expected by `filter_create_ext()`.
This is undefined behavior in C, correct operation is not guaranteed. In fact, it causes flex to crash on Apple M1 when GCC is used - the loop is not terminated when it should, instead, it keeps running, corrupting the argument list for invoking m4. As a result, it creates the following error:
> flex: fatal internal error, exec of gm4 failed
This commit fixes the problem by explicitly casting the value `0` to the correct pointer type `(char *)`. According to Rich Felker, the primary author of musl libc, [type casting …
=> Fix Issue #539 crash on Apple M1 by casting 0 to (char *) explicitly

tests/testwrapper.sh
that was used in older versions of the script, but now seems to be only set to zero here and not used anywhere
=> remove unused DO_COMPARISON

doc/Makefile.am
- .gitignore adjustments for WIN32
- typo
- remove hard-wired bison lookup, check for "GNU Bison" in $YACC's version output instead
- removed output-beautification of YACC and INDENT
- test(quotes): Add after action comment tests for m4quotes.
- Fix #539 crash on Apple M1 by casting 0 to (char *) explicitly
- Correctly refer to ctrl.traceline_template:
- remove unused DO_COMPARISON
- docs: Add CONTRIBUTING manual.
- docs(contrib): Add CONTRIBUTING.md to EXTRA_DIST.
- doc(contrib): Alphabetize commit types
- fix(build): build man page when cross compiling
=> build man page when cross compiling

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
Fixes #562.
As described in the issue, this PR adds read-only permissions to flex's workflows. This reduces the risk of supply-chain attacks via the project's CI/CD infrastructure.
=>  ci: Add read-only permissions to workflows

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml
Fixes #581.
This PR hash-pins GitHub Actions to protect the project from potential supply-chain threats.
The Actions will be updated by dependabot. dependabot will send a single PR updating all Actions with new versions at once.
=> Hash-pin GitHub Actions, keep them updated with dependabot

src/c99-flex.skl, src/cpp-flex.skl
This cleans up the warnings encountered when trying to build QuakeForge with the git version of flex.
=> Cleanup warnings

src/scan.l, tests/.gitignore, tests/Makefile.am, tests/lineno_generated.l, tests/lineno_generated.l.in
An indented code block would cause the subsequent all subsequent code block line numbers (including its own) to be out by one.
For example, the following would cause the line number for the `BEGIN` code block to have the line number for the `warning` code block. This would also affect the code in the final section after the second `%%`.
%%
yyflexdebug = 0;
grab_frame = GRAB_FRAME;
grab_other = GRAB_OTHER;
grab_write = GRAB_WRITE;
yylval->pointer = 0;// ensure pointer vals are null
"/*"        { BEGIN (COMMENT); }
<COMMENT>"/*" { warning (0, "nested /* in comment"); }
=> Skip linenum increment for indented code blocks

doc/flex.texi
This fixes issue 609, https://github.com/westes/flex/issues/609
The regex example in section A.4.3 Quoted Constructs of the Flex manual is wrong for both C- and C++-style comments
```
("/*"([^*]|"*"[^/])*"*/")|("/"(\\\n)*"/"[^\n]*)}
```
The C portion of the regex fails to recognize valid C comments like `/* text ** more text */` and fails to reject invalid comments like `/* comment 1 **/ invalid missing comment start */`
Also the C++ portion of the regex fails to recognize valid C++ multiline comments containing escaped newlines after comment start like
```c++
// multiline \
comment 1
```
The correct regex for C and C++ comments is
```
("/*"([^*]|"*"[^*/])*"*"+"/")|("/"(\\\n)*"/"((\\\n)|[^\n])*)
```
or
```
(?x: ( "/*" ( [^*] | "*"+ [^*/] )* "*"+ "/" ) | ( "/" (\\ \n)* "/" ( (\\ \n) | …
```
=> Issue 609: Fix wrong example regex for C- and C++-style comments

src/gen.c
Correct fullspeed table size computation from 'tblend + numecs + 1' to 'tblend + 2 + 1' to avoid allocating extra space that is never initialized.
Add temporary breadcrumbs to lex.yy.c to aid in checking generated scanners.
This passes the Flex test suite. Requesting community help to check additional -CF -8 scanners for unforeseen impacts.
Refs: #628
=> fix: Correct fullspeed table size.

INSTALL.md
Clarify and expand tool dependency info in INSTALL.md, particularly with respect to GNU tool variants. Describe minimal troubleshooting steps for failed builds on non-Debian systems.
Refs: #632
=> docs: Clarify GNU tool dependencies.

doc/flex.texi
The proper way to use a pure parser since 2.7 (2012-12-12) is "%define api.pure full".  The proper way to pass params since 3.0 (2013-07-25) is "%param".
=> doc: modernize Bison snippets

src/mkskel.sh
(This is a follow-up to #353 . I can't reopen the old PR, so I file another one to address my point.)
Replace the `$'\r'` quoting in commit
c674b5faa3419032a6c41cc150488866f3b3cff9 with a portable alternative `` cr=`printf '\r'` ``
Although `$' '` (dollar-single-quote) quoting is proposed for inclusion in POSIX, we have not seen it in a published standard yet, so it is best to avoid it for now.
=> build: Use portable alternative to $'\r' in mkskel.sh

src/Makefile.am
1. Correct skeleton headers dependencies
2. Don't use BUILT_SOURCES for skeleton files 
3. Let "make mostlyclean" delete "*-flex.h"
=> build: Makefile improvements with skeleton sources

src/.gitignore, src/Makefile.am
(Split from PR #321)
Change the generating rules of scan.c (in dist-hook) and stage1scan.c
so that the source and output file names in #line directives are fixed.
This would allow the scanner results be comparable to each other.
Also in --disable-bootstrap build, the flex binary will now be built
with scan.c directly - no more sedding.
=> build: Deterministic scan.c and bootstrap byte comparison check

src/scan.l
AC_PROG_LEX puts a space between yymore and its ()s causing the yymore check to fail and thus break configure.
=> Allow white space in yymore and yyreject checks

src/c99-flex.skl, src/cpp-flex.skl, src/go-flex.skl
This PR fixes #103 by adding error messages (either `yypanic()` or `YY_FATAL_ERROR`) as a default case in switch statements that check against the return value of `yy_get_next_buffer()`.
Since `yy_get_next_buffer()` is defined to return only one of three values, and all these switch statements have cases for all of these values, it would be an error if execution fell through to the default case. Additionally, adding these statements helps future-proof the codebase if `yy_get_next_buffer()` is ever modified.
=> Add error messages to unreachable ends of switch statements

src/c99-flex.skl, src/cpp-flex.skl, src/go-flex.skl
We expect to have room for 2 EOB chars, but in this particular realloc
path this only works because yy_n_chars tends to be large enough for
1.5x its value to have room for our 2 EOB chars.
That said, clang-6's static analyzer does produce a warning about this
("Use of zero-allocated memory", meaning realloc with size=0) because it
goes by the assumption that yy_n_chars and number_to_move could be 0.
While this is somewhat bogus, it does make sense to just put the "+ 2"
here and be done with it.  AFAICS, this is the correct thing to do here
after all.
Signed-off-by: David Lamparter <equinox@diac24.net>
=> scanner: consistently +2 to realloc size for EOB

src/c99-flex.skl, src/cpp-flex.skl, src/go-flex.skl
=> scanner: fix buffer stack popping in yylex_destroy

src/Makefile.am
In src/Makefile.am, remove `flex_CFLAGS` variable, and append `$(WARNINGFLAGS)` to `AM_CFLAGS`. The use of `flex_CFLAGS` has forced Automake to rename flex's object files (.o) to have a 'flex-' prefix. By preventing the rename, the generated src/Makefile.in can be about 37 kB smaller.
=> build: Append $(WARNINGFLAGS) to AM_CFLAGS

doc/Makefile.am
Two commits:
* Use a more portable expression for the 'flex.1' man page on flex program.
* Fix the program name for the man page generation.
See the commit descriptions for details.
=> build: Generate man page with fixed program name 

doc/Makefile.am
A build system regression from 3c70fb6932fdc61bddf8371400b6582c2fd5a0e9.
When `help2man` is invoked with a program path without the directory prefix (such as "./"), it might launch a program installed on the builder's system instead of the program just compiled in the working directory.
Reproducible on a CI server (example build log: https://github.com/Explorer09/flex/actions/runs/9018798317/job/24780203568)
1. Have an old version of flex installed on the builder's system ("`apt install flex`" or similar command from your package manager)
2. Hack src/main.c to alter some help text ([like this](https://github.com/Explorer09/flex/commit/ae0cc2f90775db55e8ec79f505ca075813d82878))
3. Build flex and the man page with `rm -f doc/flex.1 && ./configure && make`
4. `cat doc/flex.1` and see the man …
=> build: Correct program path in doc/Makefile.am

configure.ac
Replace two obsolete Autoconf macro uses that would trigger warnings in Autoconf 2.70.
The minimum required versions of the Autotools remain the same.
@westes I noticed your private branch and I think this is what you are wishing to do when updating the configure script.
=> fix(build): Replace obsolete Autoconf macros

configure.ac, m4/ax_prog_cc_for_build.m4
The ax_prog_cc_for_build.m4 module from upstream contains a typo fix. Beyond that, there are no code changes.
(Follow-up of #649)
=> build: Update ax_prog_cc_for_build.m4 with upstream

tests/Makefile.am
With sufficient parallelism and `make --shuffle` to reorder builds the test suite occasionally fails to build with errors like this:
tests/bison_yylval_parser.y:36:10: fatal error: bison_yylval_scanner.h: No such file or directory
36 | #include "bison_yylval_scanner.h"
Solve this by adding the missing dependencies to the *_parser.o targets on the _scanner.h files.
=> build(tests): add missing parser->scanner dependencies
